const users = [
    {
      email: "user1@example.com",
      name: "User One",
      username: "userone",
      title: "Title One",
      bio: "Bio One",
      city: "City One",
      zipcode: "12345",
      location: { latitude: 34.0522, longitude: -118.2437 },
      skills: ["JavaScript", "Node.js"],
      interests: ["coding", "hiking"],
      intentions: ["learn more about AI", "travel more"],
      contributions: ["open source projects"],
      media: ["media1", "media2"],
      opportunities: ["opportunity1", "opportunity2"],
      legacy_keys: ["legacy1", "legacy2"]
    },
    {
      email: "user2@example.com",
      name: "User Two",
      username: "usertwo",
      title: "Title Two",
      bio: "Bio Two",
      city: "City Two",
      zipcode: "23456",
      location: { latitude: 40.7128, longitude: -74.0060 },
      skills: ["Python", "Django"],
      interests: ["photography", "music"],
      intentions: ["start a blog", "learn guitar"],
      contributions: ["blog articles"],
      media: ["media3", "media4"],
      opportunities: ["opportunity3", "opportunity4"],
      legacy_keys: ["legacy3", "legacy4"]
    },
    {
      email: "user3@example.com",
      name: "User Three",
      username: "userthree",
      title: "Title Three",
      bio: "Bio Three",
      city: "City Three",
      zipcode: "34567",
      location: { latitude: 51.5074, longitude: -0.1278 },
      skills: ["HTML", "CSS"],
      interests: ["design", "painting"],
      intentions: ["learn to code", "travel the world"],
      contributions: ["design projects"],
      media: ["media5", "media6"],
      opportunities: ["opportunity5", "opportunity6"],
      legacy_keys: ["legacy5", "legacy6"]
    },
    {
        email: "user4@example.com",
        name: "User Four",
        username: "userfour",
        title: "Title Four",
        bio: "Bio Four",
        city: "City Four",
        zipcode: "45678",
        location: { latitude: 48.8566, longitude: 2.3522 },
        skills: ["React", "Redux"],
        interests: ["gaming", "reading"],
        intentions: ["improve coding skills", "write a book"],
        contributions: ["tutorials"],
        media: ["media7", "media8"],
        opportunities: ["opportunity7", "opportunity8"],
        legacy_keys: ["legacy7", "legacy8"]
      },
      {
        email: "user5@example.com",
        name: "User Five",
        username: "userfive",
        title: "Title Five",
        bio: "Bio Five",
        city: "City Five",
        zipcode: "56789",
        location: { latitude: 35.6895, longitude: 139.6917 },
        skills: ["Vue.js", "Nuxt.js"],
        interests: ["cooking", "traveling"],
        intentions: ["learn a new language", "explore cultures"],
        contributions: ["recipes"],
        media: ["media9", "media10"],
        opportunities: ["opportunity9", "opportunity10"],
        legacy_keys: ["legacy9", "legacy10"]
      },
      {
        email: "user6@example.com",
        name: "User Six",
        username: "usersix",
        title: "Title Six",
        bio: "Bio Six",
        city: "City Six",
        zipcode: "67890",
        location: { latitude: -33.8688, longitude: 151.2093 },
        skills: ["Java", "Spring Boot"],
        interests: ["running", "technology"],
        intentions: ["complete a marathon", "start a tech blog"],
        contributions: ["open source libraries"],
        media: ["media11", "media12"],
        opportunities: ["opportunity11", "opportunity12"],
        legacy_keys: ["legacy11", "legacy12"]
      },
      {
        email: "user7@example.com",
        name: "User Seven",
        username: "userseven",
        title: "Title Seven",
        bio: "Bio Seven",
        city: "City Seven",
        zipcode: "78901",
        location: { latitude: 52.5200, longitude: 13.4050 },
        skills: ["Go", "Docker"],
        interests: ["cycling", "art"],
        intentions: ["participate in a bike race", "visit art museums"],
        contributions: ["devops pipelines"],
        media: ["media13", "media14"],
        opportunities: ["opportunity13", "opportunity14"],
        legacy_keys: ["legacy13", "legacy14"]
      },
      {
        email: "user8@example.com",
        name: "User Eight",
        username: "usereight",
        title: "Title Eight",
        bio: "Bio Eight",
        city: "City Eight",
        zipcode: "89012",
        location: { latitude: 55.7558, longitude: 37.6173 },
        skills: ["Ruby", "Rails"],
        interests: ["gardening", "writing"],
        intentions: ["publish a novel", "grow a vegetable garden"],
        contributions: ["technical blogs"],
        media: ["media15", "media16"],
        opportunities: ["opportunity15", "opportunity16"],
        legacy_keys: ["legacy15", "legacy16"]
      },
      {
        email: "user9@example.com",
        name: "User Nine",
        username: "usernine",
        title: "Title Nine",
        bio: "Bio Nine",
        city: "City Nine",
        zipcode: "90123",
        location: { latitude: 37.7749, longitude: -122.4194 },
        skills: ["C++", "Qt"],
        interests: ["robotics", "chess"],
        intentions: ["build a robot", "compete in chess tournaments"],
        contributions: ["open source software"],
        media: ["media17", "media18"],
        opportunities: ["opportunity17", "opportunity18"],
        legacy_keys: ["legacy17", "legacy18"]
      },
      {
        email: "user10@example.com",
        name: "User Ten",
        username: "userten",
        title: "Title Ten",
        bio: "Bio Ten",
        city: "City Ten",
        zipcode: "01234",
        location: { latitude: 41.9028, longitude: 12.4964 },
        skills: ["Swift", "iOS Development"],
        interests: ["app development", "soccer"],
        intentions: ["release an app", "join a soccer league"],
        contributions: ["app store apps"],
        media: ["media19", "media20"],
        opportunities: ["opportunity19", "opportunity20"],
        legacy_keys: ["legacy19", "legacy20"]
      },
  ];
  
  const events = [
    {
      topic_id: "exampleTopicId1",
      name: "Event One",
      description: "Event One Description",
      flags: {
        is_skill: true,
        is_interest: false,
        is_intention: false,
        is_in_person: true,
        is_beginner: true,
        is_intermediate: false,
        is_advanced: false,
        is_contribution: false
      },
      user_references: [],
      required_skills: ["public speaking"],
      root_event: true,
      modified_by: "",
      modified_at: new Date(),
      change_description: "Initial creation",
      attendees: [],
      participation_status: [],
      categories: ["education", "technology"],
      feedback: [],
      external_ids: ["google_calendar_event_id"],
      languages_supported: ["English"],
      location_specifics: {
        country: "USA",
        region: "California",
        city: "Los Angeles",
        latitude: 34.0522,
        longitude: -118.2437
      },
      sustainability_focus: ["education"],
      partner_organizations: ["org1"],
      collaboration_level: "local",
      tech_requirements: ["projector"],
      tools_provided: ["handouts"],
      governance_model: "community-led",
      funding_source: "sponsorship",
      roles: ["admin"],
      permissions: ["create_event"],
      preferred_language: "English"
    },
    {
      topic_id: "exampleTopicId2",
      name: "Event Two",
      description: "Event Two Description",
      flags: {
        is_skill: false,
        is_interest: true,
        is_intention: false,
        is_in_person: false,
        is_beginner: false,
        is_intermediate: true,
        is_advanced: false,
        is_contribution: false
      },
      user_references: [],
      required_skills: ["teamwork"],
      root_event: true,
      modified_by: "",
      modified_at: new Date(),
      change_description: "Initial creation",
      attendees: [],
      participation_status: [],
      categories: ["health", "wellness"],
      feedback: [],
      external_ids: ["zoom_event_id"],
      languages_supported: ["Spanish"],
      location_specifics: {
        country: "USA",
        region: "New York",
        city: "New York",
        latitude: 40.7128,
        longitude: -74.0060
      },
      sustainability_focus: ["community"],
      partner_organizations: ["org2"],
      collaboration_level: "national",
      tech_requirements: ["microphone"],
      tools_provided: ["workbook"],
      governance_model: "leader-led",
      funding_source: "donations",
      roles: ["member"],
      permissions: ["view_event"],
      preferred_language: "Spanish"
    },
    {
      topic_id: "exampleTopicId3",
      name: "Event Three",
      description: "Event Three Description",
      flags: {
        is_skill: false,
        is_interest: false,
        is_intention: true,
        is_in_person: true,
        is_beginner: false,
        is_intermediate: false,
        is_advanced: true,
        is_contribution: false
      },
      user_references: [],
      required_skills: ["critical thinking"],
      root_event: true,
      modified_by: "",
      modified_at: new Date(),
      change_description: "Initial creation",
      attendees: [],
      participation_status: [],
      categories: ["science", "research"],
      feedback: [],
      external_ids: ["webinar_event_id"],
      languages_supported: ["French"],
      location_specifics: {
        country: "Canada",
        region: "Ontario",
        city: "Toronto",
        latitude: 43.651070,
        longitude: -79.347015
      },
      sustainability_focus: ["research"],
      partner_organizations: ["org3"],
      collaboration_level: "global",
      tech_requirements: ["computer"],
      tools_provided: ["slides"],
      governance_model: "self-organized",
      funding_source: "grants",
      roles: ["participant"],
      permissions: ["join_event"],
      preferred_language: "French"
    },
    {
        topic_id: "exampleTopicId4",
        name: "Event Four",
        description: "Event Four Description",
        flags: {
          is_skill: true,
          is_interest: true,
          is_intention: false,
          is_in_person: true,
          is_beginner: false,
          is_intermediate: true,
          is_advanced: false,
          is_contribution: false
        },
        user_references: [],
        required_skills: ["networking"],
        root_event: true,
        modified_by: "",
        modified_at: new Date(),
        change_description: "Initial creation",
        attendees: [],
        participation_status: [],
        categories: ["business", "entrepreneurship"],
        feedback: [],
        external_ids: ["eventbrite_event_id"],
        languages_supported: ["German"],
        location_specifics: {
          country: "Germany",
          region: "Berlin",
          city: "Berlin",
          latitude: 52.5200,
          longitude: 13.4050
        },
        sustainability_focus: ["business"],
        partner_organizations: ["org4"],
        collaboration_level: "international",
        tech_requirements: ["laptop"],
        tools_provided: ["networking guide"],
        governance_model: "community-led",
        funding_source: "membership fees",
        roles: ["facilitator"],
        permissions: ["organize_event"],
        preferred_language: "German"
      },
      {
        topic_id: "exampleTopicId5",
        name: "Event Five",
        description: "Event Five Description",
        flags: {
          is_skill: false,
          is_interest: false,
          is_intention: true,
          is_in_person: false,
          is_beginner: true,
          is_intermediate: false,
          is_advanced: false,
          is_contribution: true
        },
        user_references: [],
        required_skills: ["writing"],
        root_event: true,
        modified_by: "",
        modified_at: new Date(),
        change_description: "Initial creation",
        attendees: [],
        participation_status: [],
        categories: ["literature", "creative writing"],
        feedback: [],
        external_ids: ["meetup_event_id"],
        languages_supported: ["English"],
        location_specifics: {
          country: "UK",
          region: "England",
          city: "London",
          latitude: 51.5074,
          longitude: -0.1278
        },
        sustainability_focus: ["education"],
        partner_organizations: ["org5"],
        collaboration_level: "local",
        tech_requirements: ["tablet"],
        tools_provided: ["writing prompts"],
        governance_model: "leader-led",
        funding_source: "entry fees",
        roles: ["speaker"],
        permissions: ["manage_event"],
        preferred_language: "English"
      },
      {
        topic_id: "exampleTopicId6",
        name: "Event Six",
        description: "Event Six Description",
        flags: {
          is_skill: true,
          is_interest: true,
          is_intention: false,
          is_in_person: true,
          is_beginner: false,
          is_intermediate: true,
          is_advanced: false,
          is_contribution: false
        },
        user_references: [],
        required_skills: ["public speaking"],
        root_event: true,
        modified_by: "",
        modified_at: new Date(),
        change_description: "Initial creation",
        attendees: [],
        participation_status: [],
        categories: ["education", "technology"],
        feedback: [],
        external_ids: ["google_calendar_event_id"],
        languages_supported: ["English"],
        location_specifics: {
          country: "USA",
          region: "California",
          city: "Los Angeles",
          latitude: 34.0522,
          longitude: -118.2437
        },
        sustainability_focus: ["education"],
        partner_organizations: ["org1"],
        collaboration_level: "local",
        tech_requirements: ["projector"],
        tools_provided: ["handouts"],
        governance_model: "community-led",
        funding_source: "sponsorship",
        roles: ["admin"],
        permissions: ["create_event"],
        preferred_language: "English"
      },
      {
        topic_id: "exampleTopicId7",
        name: "Event Seven",
        description: "Event Seven Description",
        flags: {
          is_skill: false,
          is_interest: true,
          is_intention: false,
          is_in_person: false,
          is_beginner: false,
          is_intermediate: true,
          is_advanced: false,
          is_contribution: false
        },
        user_references: [],
        required_skills: ["teamwork"],
        root_event: true,
        modified_by: "",
        modified_at: new Date(),
        change_description: "Initial creation",
        attendees: [],
        participation_status: [],
        categories: ["health", "wellness"],
        feedback: [],
        external_ids: ["zoom_event_id"],
        languages_supported: ["Spanish"],
        location_specifics: {
          country: "USA",
          region: "New York",
          city: "New York",
          latitude: 40.7128,
          longitude: -74.0060
        },
        sustainability_focus: ["community"],
        partner_organizations: ["org2"],
        collaboration_level: "national",
        tech_requirements: ["microphone"],
        tools_provided: ["workbook"],
        governance_model: "leader-led",
        funding_source: "donations",
        roles: ["member"],
        permissions: ["view_event"],
        preferred_language: "Spanish"
      },
      {
        topic_id: "exampleTopicId8",
        name: "Event Eight",
        description: "Event Eight Description",
        flags: {
          is_skill: true,
          is_interest: true,
          is_intention: false,
          is_in_person: true,
          is_beginner: false,
          is_intermediate: true,
          is_advanced: false,
          is_contribution: false
        },
        user_references: [],
        required_skills: ["networking"],
        root_event: true,
        modified_by: "",
        modified_at: new Date(),
        change_description: "Initial creation",
        attendees: [],
        participation_status: [],
        categories: ["business", "entrepreneurship"],
        feedback: [],
        external_ids: ["eventbrite_event_id"],
        languages_supported: ["German"],
        location_specifics: {
          country: "Germany",
          region: "Berlin",
          city: "Berlin",
          latitude: 52.5200,
          longitude: 13.4050
        },
        sustainability_focus: ["business"],
        partner_organizations: ["org4"],
        collaboration_level: "international",
        tech_requirements: ["laptop"],
        tools_provided: ["networking guide"],
        governance_model: "community-led",
        funding_source: "membership fees",
        roles: ["facilitator"],
        permissions: ["organize_event"],
        preferred_language: "German"
      },
      {
        topic_id: "exampleTopicId9",
        name: "Event Nine",
        description: "Event Nine Description",
        flags: {
          is_skill: false,
          is_interest: false,
          is_intention: true,
          is_in_person: false,
          is_beginner: true,
          is_intermediate: false,
          is_advanced: false,
          is_contribution: true
        },
        user_references: [],
        required_skills: ["writing"],
        root_event: true,
        modified_by: "",
        modified_at: new Date(),
        change_description: "Initial creation",
        attendees: [],
        participation_status: [],
        categories: ["literature", "creative writing"],
        feedback: [],
        external_ids: ["meetup_event_id"],
        languages_supported: ["English"],
        location_specifics: {
          country: "UK",
          region: "England",
          city: "London",
          latitude: 51.5074,
          longitude: -0.1278
        },
        sustainability_focus: ["education"],
        partner_organizations: ["org5"],
        collaboration_level: "local",
        tech_requirements: ["tablet"],
        tools_provided: ["writing prompts"],
        governance_model: "leader-led",
        funding_source: "entry fees",
        roles: ["speaker"],
        permissions: ["manage_event"],
        preferred_language: "English"
      },
      {
        topic_id: "exampleTopicId10",
        name: "Event Ten",
        description: "Event Ten Description",
        flags: {
          is_skill: true,
          is_interest: false,
          is_intention: true,
          is_in_person: true,
          is_beginner: false,
          is_intermediate: false,
          is_advanced: true,
          is_contribution: false
        },
        user_references: [],
        required_skills: ["critical thinking"],
        root_event: true,
        modified_by: "",
        modified_at: new Date(),
        change_description: "Initial creation",
        attendees: [],
        participation_status: [],
        categories: ["science", "research"],
        feedback: [],
        external_ids: ["webinar_event_id"],
        languages_supported: ["French"],
        location_specifics: {
          country: "Canada",
          region: "Ontario",
          city: "Toronto",
          latitude: 43.651070,
          longitude: -79.347015
        },
        sustainability_focus: ["research"],
        partner_organizations: ["org3"],
        collaboration_level: "global",
        tech_requirements: ["computer"],
        tools_provided: ["slides"],
        governance_model: "self-organized",
        funding_source: "grants",
        roles: ["participant"],
        permissions: ["join_event"],
        preferred_language: "French"
      },
  ];
  
  const categories = [
    { name: "Category One" },
    { name: "Category Two" },
    { name: "Category Three" },
    { name: "Category Four" },
    { name: "Category Five" },
    { name: "Category Six" },
    { name: "Category Seven" },
    { name: "Category Eight" },
    { name: "Category Nine" },
    { name: "Category Ten" }
  ];
  
  const media = [
    {
      event_id: "",
      url: "http://example.com/media1.jpg",
      type: "image",
      description: "An example image 1"
    },
    {
      event_id: "",
      url: "http://example.com/media2.jpg",
      type: "image",
      description: "An example image 2"
    },
    {
      event_id: "",
      url: "http://example.com/media3.jpg",
      type: "image",
      description: "An example image 3"
    },
    {
      event_id: "",
      url: "http://example.com/media4.jpg",
      type: "image",
      description: "An example image 4"
    },
    {
      event_id: "",
      url: "http://example.com/media5.jpg",
      type: "image",
      description: "An example image 5"
    },
    {
      event_id: "",
      url: "http://example.com/media6.jpg",
      type: "image",
      description: "An example image 6"
    },
    {
      event_id: "",
      url: "http://example.com/media7.jpg",
      type: "image",
      description: "An example image 7"
    },
    {
      event_id: "",
      url: "http://example.com/media8.jpg",
      type: "image",
      description: "An example image 8"
    },
    {
      event_id: "",
      url: "http://example.com/media9.jpg",
      type: "image",
      description: "An example image 9"
    },
    {
      event_id: "",
      url: "http://example.com/media10.jpg",
      type: "image",
      description: "An example image 10"
    }
  ];
  
  module.exports = {
    users,
    events,
    categories,
    media
  };
  